### ISSUE TITLE
[interaction::commandInteraction] DiscordAPIError: Unknown interaction

### ISSUE THREAD

**Issue by HealthScreeningBot-Github** [HealthScreening/HealthScreeningBot#477] opened 2022-01-06 02:27 UTC
# Error Details
- Error Type: **interaction::commandInteraction**
- Error Name: **DiscordAPIError**
- Error Message: **Unknown interaction**
- Error Occured At: **Sunday, January 2, 2022, 9:09:05 PM Eastern Standard Time**

## Error Stack Trace

```
DiscordAPIError: Unknown interaction
    at RequestHandler.execute (/home/aoyansarkar/HealthScreeningBot/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/home/aoyansarkar/HealthScreeningBot/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
    at async CommandInteraction.reply (/home/aoyansarkar/HealthScreeningBot/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:99:5)
    at async SetAuto.execute (/home/aoyansarkar/HealthScreeningBot/src/commands/setAuto.js:81:9)
    at async commandInteraction (/home/aoyansarkar/HealthScreeningBot/src/client/interactions/commandInteraction.js:40:13)
    at async HealthScreeningBotClient.oninteractionCreate (/home/aoyansarkar/HealthScreeningBot/src/client/extraClient.js:137:28)
```

## Error Metadata

```json
{
    "redacted": true
}
```

# Issue Details
- Posted By: **@PythonCoderAS**
- Posted At: **Wednesday, January 5, 2022, 9:27:45 PM Eastern Standard Time**

**Comment by PythonCoderAS** [comment] 2022-01-06 02:31
Closing as duplicate of #476

**Closed by PythonCoderAS** 2022-01-06 02:31 UTC
Labels: bug, error log bug
